jlawyerorg/j-lawyer-org

j-lawyer-client/src/com/jdimension/jlawyer/client/LoginDialog.java
=> Fix issue #724

deploy-demo.sh, j-lawyer-client/src/com/jdimension/jlawyer/client/plugins/form/FormInstancePanel.java, j-lawyer-client/src/com/jdimension/jlawyer/client/plugins/form/FormPlugin.java
=> Fix forms issue with potential data loss 

j-lawyer-client/src/de/costache/calendar/CalendarPanel.java, j-lawyer-client/src/de/costache/calendar/model/CalendarEvent.java, j-lawyer-client/src/de/costache/calendar/model/EventType.java, j-lawyer-client/src/de/costache/calendar/ui/DayContentPanel.java
Closes #1589
Events are now sorted in the order Termin -> Frist -> WV
=> Add sorting to calendar entries in month view

j-lawyer-client/src/de/costache/calendar/JCalendar.java, j-lawyer-client/src/de/costache/calendar/ui/ContentPanel.java, j-lawyer-client/src/de/costache/calendar/ui/HeaderPanel.java, j-lawyer-client/src/de/costache/calendar/ui/strategy/MonthDisplayStrategy.java
feat: Update calendar to handle mouse wheel scrolling in month view
- Added MouseWheelListener to ContentPanel to handle interval changes via mouse wheel scrolling when in month view.
- Updated JCalendar to include getHeaderPanel() method for accessing the HeaderPanel.
- Ensured the intervalLabel in HeaderPanel updates correctly when the interval changes via mouse wheel scrolling or button actions.
- Refactored MonthDisplayStrategy to properly handle and update the interval display.
=> [FEATURE] Usability im Kalender: Scrollen durch Monate mittels Mausrad

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/ConflictingEventsDialog.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/EditOrDuplicateEventDialog.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/PartiesPanel.java
=> UI fixes: Focus auf Button und Eingabefelder; Tooltip erweitert für Beteiligtenmatrix

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/AddNoteDialog.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/InvoiceDialog.form, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/InvoiceDialog.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/InvolvedPartyEntryPanel.form, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/InvolvedPartyEntryPanel.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/PartiesPanel.java, j-lawyer-client/src/com/jdimension/jlawyer/client/utils/FindRouteToAddress.java, j-lawyer-client/src/themes/colors/DefaultColorTheme.java
added: Show route to address and address in OpenStreetMap
For out-of-town appointments, the travel time can be quickly  estimated to make scheduling easier.
----------------------------------------------
added: Adresse in OpenStreetMap anzeigen
added: Route zur Adresse in OpenStreetMap anzeigen
Bei auswärtigen Terminen kann schnell die Fahrtzeit abgeschätzt werden, um die Terminplanung zu erleichtern.
betrifft #902 und #1326
Icons müssten noch hinzugefügt werden. 
@j-dimension in meiner Testumgebung öffnet der Browser nicht, kannst du das testen?
=> added: Show route to address and address in OpenStreetMap

j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
=> Signature below reply but above quoted message when replying to mail

j-lawyer-client/src/com/jdimension/jlawyer/client/LoginDialog.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/addresses/AddressPanel.form, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/addresses/AddressPanel.java
Minor commits for the ui.
close #2072 
close #2194
=> Fix/some UI fixes

j-lawyer-client/src/com/jdimension/jlawyer/client/mail/MailContentUI.form, j-lawyer-client/src/com/jdimension/jlawyer/client/mail/MailContentUI.java
Implement mouse listener to copy text to clipboard for  lblSubject, lblFrom and lblTo labels.
=> Add copy-to-clipboard functionality for email labels

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/NewEventPanel.form, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/NewEventPanel.java
=> Fix: Set fixed size for txtReviewReason to prevent JPanel expansion

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/NewEventPanel.form, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/NewEventPanel.java
Reverts jlawyerorg/j-lawyer-org#2530
=> Revert "Fix: Set fixed size for txtReviewReason to prevent JPanel expansion"

j-lawyer-client/src/themes/FlatIntelliJLaf.properties
=> increased row height in tables from 20 to 25 - for whole application

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/AddNoteDialog.java
=> fixes sorting of case and document tags

j-lawyer-client/src/com/jdimension/jlawyer/client/assistant/AssistantAccess.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/ArchiveFilePanel.java, j-lawyer-client/src/com/jdimension/jlawyer/client/mail/MailContentUI.java
added seperatorin menus between categories
added alphabetical order in menu showing Ingo categories
#2578
=> added alphabetical order in menu showing Ingo categories - 

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/PdfImageScrollingPanel.java, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/PdfPageImage.form, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/PdfPageImage.java
=> added button to delete single pdf pages in documentviewer

j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
@j-dimension sollte jetzt klappen
=> added "from" to compose call

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/ArchiveFilePanel.form, j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/ArchiveFilePanel.java
- Add new menu action to split PDF documents at specified page numbers
- Implement user dialog for comma-separated split page input
- Create new documents for each split part
=> feat: Add PDF split functionality

j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.form, j-lawyer-client/src/com/jdimension/jlawyer/client/mail/SendEmailDialog.java
=> Add: Interactive email template search feature

j-lawyer-server/j-lawyer-io/src/java/org/jlawyer/io/rest/v3/CasesEndpointLocalV3.java, j-lawyer-server/j-lawyer-io/src/java/org/jlawyer/io/rest/v3/CasesEndpointV3.java, j-lawyer-server/j-lawyer-server-ejb/src/java/com/jdimension/jlawyer/services/ArchiveFileServiceLocal.java
=> added: endpoints for creating and deleting folders in given case

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/SearchAndAssignDialog.java
Problem: Im Dialog „Akte suchen“ verschob sich der JSplitPane‑Trenner unter Linux
bei jedem Öffnen weiter nach rechts. Ursache war, dass beim Initialisieren zuerst
ein Standardwert (0,7) gesetzt und anschließend zusätzliche Layout-/Resize‑Änderungen
(Baumaufbau, Scrollbars) ausgelöst wurden. Diese programmgesteuerten Verschiebungen wurden
sofort als Nutzeränderungen persistiert und beim nächsten Öffnen als größerer Pixelwert
wiederhergestellt.
Lösung: Der Standard‑Divider wird nur gesetzt, wenn kein gespeicherter Wert existiert.
Die Persistierung der Divider‑Position erfolgt erst nach expliziter Nutzerinteraktion
(Mausdrag) und nicht mehr während programmatischer Initialisierung. Damit werden
Initialisierungs‑Drifts nicht gespeichert und die Trennerposition bleibt über Öffnungen
stabil. …
=> fixed: divider drift predom. in gtk based linux

j-lawyer-client/src/com/jdimension/jlawyer/client/components/QuickDateSelectionPanel.form, j-lawyer-client/src/com/jdimension/jlawyer/client/components/QuickDateSelectionPanel.java, j-lawyer-client/src/de/costache/calendar/ui/ContentPanel.java, j-lawyer-client/src/de/costache/calendar/ui/DayContentPanel.java, j-lawyer-client/src/de/costache/calendar/ui/DayPanel.java, j-lawyer-client/src/de/costache/calendar/ui/strategy/DayDisplayStrategy.java, j-lawyer-client/src/de/costache/calendar/ui/strategy/MonthDisplayStrategy.java, j-lawyer-client/src/de/costache/calendar/ui/strategy/WeekDisplayStrategy.java
completes #1478
Branch - Name bitte nicht beachten, der passt nicht.
=> added: quickselect buttons for 3W and 1M #1478; fixes for Calendar UI

j-lawyer-client/src/com/jdimension/jlawyer/client/desktop/DesktopPanel.form, j-lawyer-client/src/com/jdimension/jlawyer/client/desktop/DesktopPanel.java, j-lawyer-client/src/com/jdimension/jlawyer/client/desktop/ReviewsDueTimerTask.java, j-lawyer-client/src/com/jdimension/jlawyer/client/desktop/TaggedTimerTask.java
=> added: filtering for users in tag section of desktop - #3029

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/EditOrDuplicateEventDialog.java, j-lawyer-client/src/com/jdimension/jlawyer/client/settings/ClientSettings.java, j-lawyer-client/src/de/costache/calendar/CalendarPanel.java, j-lawyer-client/src/de/costache/calendar/ui/strategy/MonthDisplayStrategy.java, j-lawyer-client/src/de/costache/calendar/ui/strategy/WeekDisplayStrategy.java
=> added: now events can be edited in calendar, no need to enter case

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/ExportAsPdfMergeStep.java
=> ExportAsPDFMerge asks for new name if file already exists

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/reporting/DynamicReportContainerPanel.java
=> fixed splitter

j-lawyer-client/src/org/jmarkdownviewer/jmdviewer/resources/github-reduced.css
Mit neuem Wert ist die Darstellung kompakter.
fix für #3115
=> reduced margin - MD zu HTML Konvertierung

j-lawyer-client/src/com/jdimension/jlawyer/client/editors/documents/viewer/MarkdownPanel.java
=> fixed markdown formatting

j-lawyer-client/src/de/costache/calendar/ui/DayContentPanel.java, j-lawyer-client/src/de/costache/calendar/util/CalendarUtil.java
=> better rendering of consecutive events
